import React from "react";

export default function Caution() {
    return (
        <>
            <header className="mb-16 text-center animate-fade-in">
                <div className="inline-flex py-3 px-3 rounded-full bg-amber-100 text-amber-600 mb-6 heartbeat">
                    <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 24 24" fill="none"
                        stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                        <path d="m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3Z" />
                        <line x1="12" y1="9" x2="12" y2="13" />
                        <line x1="12" y1="17" x2="12.01" y2="17" />
                    </svg>
                </div>
                <h1 className="text-5xl font-black mb-4">Ethical Boundaries</h1>
                <p className="text-xl text-secondary max-w-2xl mx-auto italic">Science requires integrity. Please read our
                    medical disclaimer carefully.</p>
            </header>

            <div className="max-w-4xl mx-auto space-y-12 mb-20">
                <section className="card p-10">
                    <h2 className="text-3xl font-black mb-6 text-[var(--text-main)] uppercase tracking-tighter">1. Not a Medical
                        Diagnosis</h2>
                    <p className="text-secondary text-lg leading-relaxed mb-6">
                        HeartCare AI is an experimental analytics platform. The predictions generated by our Machine
                        Learning model are strictly for **educational and research purposes**. They do not constitute a
                        medical diagnosis, clinical opinion, or professional healthcare advice.
                    </p>
                    <div className="p-6 rounded-[2rem] flex items-center gap-6" style={{ boxShadow: "var(--clay-input-shadow)" }}>
                        <div className="text-amber-600 text-4xl">⚕️</div>
                        <p className="text-sm font-bold text-sky-blue leading-normal">
                            Always consult a certified cardiologist or healthcare professional for any medical concerns.
                            Never disregard professional advice based on the output of this AI system.
                        </p>
                    </div>
                </section>

                <section className="grid grid-cols-1 md:grid-cols-2 gap-8">
                    <div className="card p-8">
                        <h3 className="text-xl font-bold mb-4 flex items-center gap-2 text-primary">
                            <span className="text-2xl">📉</span> Probabilistic Nature
                        </h3>
                        <p className="text-sm text-secondary leading-relaxed">
                            Artificial Intelligence works on probability, not biological certainty. Factors not included in
                            the dataset (like genetics or rare pathologies) can significantly alter real-world
                            cardiovascular health.
                        </p>
                    </div>
                    <div className="card p-8">
                        <h3 className="text-xl font-bold mb-4 flex items-center gap-2 text-primary">
                            <span className="text-2xl">🔒</span> Data Privacy
                        </h3>
                        <p className="text-sm text-secondary leading-relaxed">
                            We prioritize your security. Data entered into the prediction form is processed locally to
                            generate immediate results. We do not store or sell your personal health bio-markers.
                        </p>
                    </div>
                </section>

                <section className="card p-10 bg-gradient-to-br from-[var(--bg-card)] to-red-50/30">
                    <h2 className="text-3xl font-black mb-6 text-[var(--text-main)] uppercase tracking-tighter">Real-World
                        Context</h2>
                    <div className="flex flex-col md:flex-row gap-8 items-center">
                        <div className="flex-1">
                            <p className="text-secondary text-lg leading-relaxed mb-6">
                                Our model achieves approximately <strong>73% accuracy</strong> in validation tests. While
                                significantly better than random chance, it is
                                <strong>not infallible</strong>.
                            </p>
                            <p className="text-secondary text-lg leading-relaxed">
                                For comparison, clinical tools like stress EKG tests have sensitivity rates ranging from
                                60-80%, often requiring angiograms for
                                true confirmation. CardioCare AI is a <strong>preliminary screening tool</strong>, meant to
                                prompt professional checkups, not replace them.
                            </p>
                        </div>
                        <div className="w-full md:w-1/3">
                            <div className="card p-6 rounded-2xl border border-white/20 text-center">
                                <div className="text-5xl font-black text-primary mb-2">73%</div>
                                <div className="text-xs font-bold text-gray-400 uppercase tracking-widest">Model Accuracy</div>
                                <div className="w-full h-1 bg-gray-200 mt-4 rounded-full overflow-hidden">
                                    <div className="h-full bg-primary w-[73%]"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>

                <section className="card p-12 text-center">
                    <h3 className="text-2xl font-black mb-4">Research Standard Acknowledgment</h3>
                    <p className="text-secondary max-w-2xl mx-auto text-sm leading-relaxed mb-8">
                        By using this tool, you acknowledge that you are interacting with a predictive model designed to
                        highlight statistical risks, which should always be validated through clinical blood tests and
                        professional examination.
                    </p>
                    <div className="flex justify-center gap-1 opacity-60 text-xs font-mono mb-2">
                        <span>PROTOCOL_V4</span><span>|</span><span>UCI_VALIDATED</span><span>|</span><span>ETHICAL_BRIDGE</span>
                    </div>
                </section>
            </div>
        </>
    );
}
